# Text Representation

In [1]:
import pandas as pd
import numpy as np

C:\Users\jaidh\build\Lib\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED


In [2]:
df = pd.read_excel(r"C:\Users\jaidh\Downloads\archive (9)\nlpdataset\nlpdataset\labelled sentences(1).xlsx")

In [3]:
df.head(5)

,Sentences,Label
0,UN Humanitarian Chief Mark Lowcock today relea...,1
1,The announcement came as the World Health Orga...,0
2,The WHO has said there is still a chance of co...,1
3,"There are now cases linked to Iran in Bahrain,...",1
4,Extensive testing in clinical trials has confi...,1


In [4]:
df.Sentences[1]

'The announcement came as the World Health Organization (WHO) upgraded the global risk of the coronavirus outbreak to "very high" ƒ?? its top level of risk assessment.'

In [8]:
df["Label"].value_counts()

Label
1    514
0    175
Name: count, dtype: int64

In [11]:
df.isnull().sum()

Sentences    0
Label        0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(2)

In [13]:
import re
def remove_tags(raw_text):
    cleaned_text = re.sub(re.compile('<.*?>'), '', raw_text)
    return cleaned_text

In [15]:
df['Sentences'] = df['Sentences'].apply(remove_tags)

In [16]:
df

,Sentences,Label
0,UN Humanitarian Chief Mark Lowcock today relea...,1
1,The announcement came as the World Health Orga...,0
2,The WHO has said there is still a chance of co...,1
3,"There are now cases linked to Iran in Bahrain,...",1
4,Extensive testing in clinical trials has confi...,1
...,...,...
684,"In November 2021, one stringent regulatory aut...",1
685,Trials in children as young as age 3 years wer...,1
686,"Covaxin, an adjuvanted inactivated vaccine dev...",1
687,The Indian regulatory authorities have given a...,1


In [17]:
df['Sentences'] = df['Sentences'].apply(lambda x:x.lower())

In [18]:
from nltk.corpus import stopwords
sw_list = stopwords.words('english')
df['Sentences'] = df['Sentences'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

In [19]:
df

,Sentences,Label
0,un humanitarian chief mark lowcock today relea...,1
1,announcement came world health organization (w...,0
2,said still chance containing virus chain trans...,1
3,"cases linked iran bahrain, iraq, kuwait oman, ...",1
4,extensive testing clinical trials confirmed ma...,1
...,...,...
684,"november 2021, one stringent regulatory author...",1
685,trials children young age 3 years completed tw...,1
686,"covaxin, adjuvanted inactivated vaccine develo...",1
687,indian regulatory authorities given approval z...,1


In [20]:
X = df.iloc[:,0:1]
y = df['Label']

In [21]:
y

0      1
1      0
2      1
3      1
4      1
      ..
684    1
685    1
686    1
687    1
688    1
Name: Label, Length: 689, dtype: int64

In [22]:
X

,Sentences
0,un humanitarian chief mark lowcock today relea...
1,announcement came world health organization (w...
2,said still chance containing virus chain trans...
3,"cases linked iran bahrain, iraq, kuwait oman, ..."
4,extensive testing clinical trials confirmed ma...
...,...
684,"november 2021, one stringent regulatory author..."
685,trials children young age 3 years completed tw...
686,"covaxin, adjuvanted inactivated vaccine develo..."
687,indian regulatory authorities given approval z...


# By One-Hot_Encoder

In [24]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

In [28]:
from sklearn.feature_extraction.text import CountVectorizer
texts = [df.Sentences[1]]
cv = CountVectorizer(binary=True)
encoded = cv.fit_transform(texts).toarray()
print(encoded)

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]


In [29]:
Sentences = [
    "cat dog",
    "dog fish",
    "cat fish dog"]
cv = CountVectorizer(binary=True)
ohe = cv.fit_transform(Sentences).toarray()
print(ohe)

[[1 1 0]
 [0 1 1]
 [1 1 1]]
